version: "3.9"

services:
  vue-app:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    container_name: vue_app
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true

  websocket-server:
    build:
      context: ./websocket-server
    container_name: websocket_server
    ports:
      - "3000:3000"
    volumes:
      - ./websocket-server:/app
      - /app/node_modules